### ISSUE TITLE
Error when trying to move frames, frames revert to default location

### ISSUE THREAD

**Issue by Raezzor** [Phanx/PhanxBuffs#10]
As title, anytime frames are moved it throws an error for me, link to pastebin [here](http://pastebin.com/iGf2pRUm). Once the frames are done being moved exiting options revert them to their default location as does locking them. Frames start out opaque as well whether locked or not and only go transparent when relocked. User on wowinterface suggested a fix in options.lua but it didn't work for me.

Edit: Hmm, redid the fix the user suggested and it worked the second time... must have been a fat finger error.

**Comment by Phanx** [comment]
Fixed in  4b3998e
