### ISSUE TITLE
Timers not displaying

### ISSUE THREAD

**Issue by 2ndHouse** [Phanx/PhanxBuffs#11]
The timers are not displaying for me upon login. I came across a fix by mistake. Opening the interface options panel fixes the timers (doesn't have to be the options for the addon, just interface options in general). Maybe some of the Phanx Buffs options are not being correctly applied until the interface options panel is open? My guess would be the max duration option is broken, but not sure.

**Comment by 2ndHouse** [comment]
It looks like some people on WoWInterface have mentioned it too. One person said taking a screenshot fixes the timers. It's like the timers need some sort of refresh to start working correctly.

**Comment by 2ndHouse** [comment]
Realized that maybe I should clarify that the icons and stack counts show correctly, just not the timer text.

**Comment by Tarkumi** [comment]
I can reproduce this bug any time ingame:
1. /reloadui
2. Use a spell/item to put a debuff on you (eg bandages)
3. Debuff icon appears but no timer.
4. Make a screenshot (or do a /console gxrestart)
5. Timer appears and will work until the next login or /reloadui (maybe instance load, i didn't test that).

**Comment by AL3x3y0** [comment]
@phanx-wow @Phanx pls fix it...
