### ISSUE TITLE
Unlocking buff-frames does not work

### ISSUE THREAD

**Issue by Qessu** [Phanx/PhanxBuffs#12]
Unlocking buff-frames does not work since patch 7.3.

1x ...s\Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox-20150112.lua:30: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: in function `PlaySound'
...s\Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox-20150112.lua:30: in function <...s\Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox.lua:28>

Locals:
(*temporary) = "igMainmenuOptionCheckBoxOff"

**Comment by skorgex** [comment]
Happening to me as well.

**Comment by khshoo** [comment]
Any chances to update this addon for 7.3? Most of the addon preferences dont work :(

**Comment by armordecai** [comment]
Updated
