### ISSUE TITLE
3.3.5a

### ISSUE THREAD

**Issue by jjbreis** [Phanx/PhanxBuffs#13]
Hey I noticed you had a version of this working for 3.3.5a, any chance you still have a mirror for it somewhere?

**Comment by Phanx** [comment]
Not specifically, but if you go to the main project page on GitHub and click on "commits", you can scroll back through the project history to find a revision from that time period.

Once you find one that looks promising, click the icon at the end of a row that looks like "<>" to view the codebase at that revision. Check the interface number in the TOC file. Then click the "clone or download" button at the top of the file list to get a ZIP of that revision, and install from that.

You'll also need libraries; look in the TOC file to see which ones. If the versions in the current release version don't work in ancient WoW versions, you'll have to repeat the process for each library that doesn't work. From memory though, I don't think any of the libraries used have changed much, or at all, so you might get lucky on that front.

Good luck.

**Comment by jjbreis** [comment]
I managed to get it to work. I can't thank you enough, thanks 👍 <3
