### ISSUE TITLE
Still a broken playsound after patch 7.3...

### ISSUE THREAD

**Issue by ZaephirMoth** [Phanx/PhanxBuffs#14]
Greetings !

  I was testing this addon when the "PlaySoundFixer" I use to detect and report stuff broken after patch 7.3 began barking : " PSF: broken PlaySound("igMainmenuOptionCheckBoxOff") called from ...r\Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox.lua:30 ". It was while activating and disactivating options ("Lock frames", etc.) in the addon's interface option menu... PSF converted the broken PlaySound to " PlaySound(SOUNDKIT[IG_MAINMENU_OPTION_CHECKBOX_OFF]) " for playback, but this is merely a temporary measure...
  The corresponding lua error which popped on screen was : 
  Message: ...r\Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox.lua:30: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: 12/08/17 01:53:40
Count: 1
Stack: ...r\Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox.lua:30: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: ?
[C]: in function `PlaySound'
...r\Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox.lua:30: in function <...r\Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox.lua:28>

Locals: 
  
  I hope this helps ! Cheers !
  Benjamin

**Comment by Phanx** [comment]
Fixed.
