### ISSUE TITLE
Options panel not displaying

### ISSUE THREAD

**Issue by 2ndHouse** [Phanx/PhanxBuffs#4]
Thanks for the Legion update, only problem I'm seeing is the options panel does not display and gives this error...

1x ...hanxConfig-OptionsPanel\PhanxConfig-OptionsPanel-20150112.lua:41: PhanxBuffs\Options-Options.lua:13: attempt to index global 'L' (a nil value)
[C]: in function `error'
...hanxConfig-OptionsPanel\PhanxConfig-OptionsPanel-20150112.lua:41: in function <...hanxConfig-OptionsPanel\PhanxConfig-OptionsPanel.lua:37>
[C]: in function`Show'
FrameXML\InterfaceOptionsFrame.lua:28: in function `InterfaceOptionsList_DisplayPanel'
FrameXML\InterfaceOptionsFrame.lua:46: in function`InterfaceOptionsListButton_OnClick'
[string "_:OnClick"]:2: in function <[string "_:OnClick"]:1>

**Comment by Phanx** [comment]
Fixed in 7.0.3.1
