### ISSUE TITLE
Timers frozen error

### ISSUE THREAD

**Issue by 2ndHouse** [Phanx/PhanxBuffs#5]
The timers for my buffs just froze, and the buff frames won't update with new buffs afterwards. Some of them display a time of "0". It could of been triggered by leaving an instance. The error:

PhanxBuffs\Buffs.lua:207: attempt to index local 'b' (a nil value)
PhanxBuffs\Buffs.lua:207: in function <PhanxBuffs\Buffs.lua:197>

PhanxBuffs\Buffs.lua:266: in function `Update'
PhanxBuffs\Buffs.lua:298: in function <PhanxBuffs\Buffs.lua:296>

**Comment by 2ndHouse** [comment]
Yeah seems to freeze on leaving an instance, and maybe when joining one too. Here is another error it threw out, pretty similar to the first one:

PhanxBuffs\Buffs.lua:198: attempt to index local 'a' (a nil value)
PhanxBuffs\Buffs.lua:198: in function <PhanxBuffs\Buffs.lua:197>

PhanxBuffs\Buffs.lua:266: in function `Update'
PhanxBuffs\Buffs.lua:298: in function <PhanxBuffs\Buffs.lua:296>

**Comment by 2ndHouse** [comment]
Similar error with debuffs too. Have duplicate frozen icons with no duration and no tooltips...

 PhanxBuffs\Debuffs.lua:207: attempt to index local 'b' (a nil value)
PhanxBuffs\Debuffs.lua:207: in function <PhanxBuffs\Debuffs.lua:205>

PhanxBuffs\Debuffs.lua:276: in function `Update'
PhanxBuffs\Debuffs.lua:327: in function <PhanxBuffs\Debuffs.lua:325>

**Comment by Phanx** [comment]
Fixed in 7.0.3.1
