### ISSUE TITLE
Duplicate buff icons

### ISSUE THREAD

**Issue by 2ndHouse** [Phanx/PhanxBuffs#7]
Seeing two of the same buff icon when zoning into areas sometimes. This screenshot is just after zoning into a raid. The tooltip reads correctly, but the icon is not correct. Not seeing any lua errors though.

![wowscrnshot_072916_212610](https://cloud.githubusercontent.com/assets/79890/17267900/304d189c-55e5-11e6-89f5-037793e085aa.jpg)

**Comment by 2ndHouse** [comment]
Don't know what's wrong with the link, keeps wanting to redirect here, have to copy and paste it.

**Comment by Phanx** [comment]
Fixed a while ago.
