### ISSUE TITLE
Not working on mage

### ISSUE THREAD

**Issue by ghost** [Phanx/PhanxBuffs#8]
Hello there,

I'm having a trouble with your addon, as it doesn't work on my mage character(s).
I've done nothing in particular. I have a character for every class, and the mage is the only one on which it doesn't work. It uses blizzard's default buff window, and locking / unlocking the PhanxBuffs unit frame, changing the size etc don't do anything. The grey panels don't appear at all.

I also removed all of my other addons to avoid any kind of conflict, with no result.

I tried creating a new mage character and had the same problem. Tried with a new rogue, and it worked, that's why I believe this issue is attached to the mage class.

Of course I have the latest version of it.

Thanks for your job anyway !

**Comment by Phanx** [comment]
The mage-specific issue was already fixed in 7.0.3.2, which was released about 3 hours ago.

**Comment by ghost** [comment]
Oh yes indeed. Thank you :)
I checked on wow curse where the last update wasn't there already, that's why I opened the issue. My bad  !
